### ISSUE TITLE
Just out of curiosity

### ISSUE THREAD

**Issue by ghost** [briansunter/haskell-rest-api#1]
How would you handle the case when the the API client sent the wrong deck ID?  

I'd do something clunky like:

```haskell

server :: Server FlashCardAPI
server = allDecksH  :<|> postDecksH :<|> getDeckByIdH
  where allDecksH = liftIO getDecks
            postDecksH deck = liftIO $ insertDeck deck
            getDeckByIdH deckId = do 
                   mdeck <- liftIO $ getDeckById deckId
                   case mdeck of
                        Nothing -> throwErr err404
                        Just d -> return d


getDeckById :: Int64 -> IO (Maybe (Entity Deck))
getDeckById i = do
  runSqlite "flashcards.sqlite" $ do
    let key = toSqlKey i :: Key Deck
    deck <- get key
    return deck

```

But its a little wierd. It would be nice to have the "business" functions live somewhere other than the IO monad.

**Comment by briansunter** [comment]
I like your solution. I definitely skimped on the error handling on this project. There are other places where I use unsafe functions like `getJust`. This project was sort of exercise in writing "readable haskell" with ample abusive of let bindings and do notation and minimal abstractions. Maybe something like a `maybeThrow404Err` wrapper function would work. I'm sure there could be some very clever integration between persistent and servant that would abstract away crud  operations, filtering via query params, pagination, etc.

**Comment by ghost** [comment]
Hmm super. Thanks for your thoughts - as I say, I was just kind of curious.

**Comment by briansunter** [comment]
this sparked my interest so I made a basic attempt at solving this in a somewhat generic way with servant-checked-exceptions.

https://github.com/briansunter/haskell-rest-api/pull/2
